### PR TITLE
[docs] WIP correct md files so MDX processor is not chocking

### PR DESCRIPTION
**Pull request by iamveritas**
[docs] WIP (work in progress) correct md files so MDX processor is not chocking

## Change Description
Fix all sorts of issues found by the docs migration process.

### CODE REVIEW

**Comment by ericpassmore** [comment]
In the file `docs/09_tutorials/01_binary-extension.md` on line 632 is the '$' intended? 
Otherwise looks good

**Comment by iamveritas** [comment]
> In the file `docs/09_tutorials/01_binary-extension.md` on line 632 is the '$' intended? Otherwise looks good

yes that is correct, a bit later down the road it is explained:
```
Note the $ after the types now; this indicates that this type is an esio::binary_extension type field.
```

**Review by ericpassmore — APPROVED** [review]
approved, reviewed title change as well

**Comment by iamveritas** [comment]
not ready to merge, it will be reopened later.

**Pull request closed without merging**
